version: '3'

services:
  # notice-app用データベース
  inmane-db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=learn55
      - MYSQL_USER=inmnuser
      - MYSQL_PASSWORD=inmnpass
      - MYSQL_DATABASE=inmane
      - TZ=Asia/Tokyo
    volumes:
      - ./inmane-db/initdb.d:/docker-entrypoint-initdb.d
      - ./inmane-db/data:/var/lib/mysql
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_bin
        --innodb_large_prefix
        --innodb_file_per_table
        --innodb_file_format=Barracuda
        --skip-character-set-client-handshake

  sonarqube:
    image: sonarqube:8.3.1-community
    
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
